# Meduza V - local install, no Docker required (Windows).
#
# Runs the whole shop from one Python virtualenv against a SQLite file:
# web + background worker + storefront. Intended for demos, evaluation and
# single-operator use on one machine.
#
#   .\installer\install-local.ps1              install and start
#   .\installer\install-local.ps1 -Port 8100   serve on another port
#   .\installer\install-local.ps1 -NoStart     set up only
#
# NOT the production path. SQLite has no row locking, so the protection against
# two customers buying the last item at the same time is weaker than on
# PostgreSQL. For a real shop use installer\install.ps1 (Docker + PostgreSQL).

[CmdletBinding()]
param(
    [int]$Port = 8000,
    [switch]$NoStart,
    [switch]$NoSeed
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$ProjectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $ProjectRoot

function Step($m) { Write-Host "==> $m" -ForegroundColor White }
function Ok($m)   { Write-Host "    + $m" -ForegroundColor Green }
function Warn($m) { Write-Host "    ! $m" -ForegroundColor Yellow }
function Die($m)  { Write-Host "`nerror: $m" -ForegroundColor Red; exit 1 }

# PowerShell 7 also runs on macOS and Linux, where a virtualenv puts its
# executables in bin/ rather than Scripts/. Resolve it rather than assume.
$OnWindows = $IsWindows -or ($PSVersionTable.PSVersion.Major -le 5)
$VenvBin = if ($OnWindows) { 'Scripts' } else { 'bin' }
$PyExe = if ($OnWindows) { 'python.exe' } else { 'python' }

Write-Host ""
Write-Host "Meduza V - local install (no Docker)" -ForegroundColor White
Write-Host $ProjectRoot -ForegroundColor DarkGray
Write-Host ""

Step 'Checking Python'
$py = $null
foreach ($candidate in @('python', 'python3', 'py')) {
    $cmd = Get-Command $candidate -ErrorAction SilentlyContinue
    if (-not $cmd) { continue }
    # `py -3` is the Windows launcher; the others are the interpreter itself.
    $probe = if ($candidate -eq 'py') { @('-3', '-c') } else { @('-c') }
    & $cmd @probe 'import sys; sys.exit(0 if sys.version_info >= (3,11) else 1)' 2>$null
    if ($LASTEXITCODE -eq 0) { $py = $cmd.Source; if ($candidate -eq 'py') { $pyArgs = @('-3') } else { $pyArgs = @() }; break }
}
if (-not $py) {
    Die "Python 3.11 or newer is required.`n    https://www.python.org/downloads/  (tick 'Add python.exe to PATH')"
}
Ok (& $py @pyArgs --version 2>&1)

Step 'Creating the virtual environment'
$Venv = Join-Path $ProjectRoot '.venv'
$VPy = Join-Path $Venv $VenvBin $PyExe
if (Test-Path $VPy) {
    Ok 'reusing existing .venv'
} else {
    & $py @pyArgs -m venv $Venv
    if ($LASTEXITCODE -ne 0) { Die 'could not create a virtualenv' }
    Ok 'created .venv'
}

Step 'Installing dependencies'
& $VPy -m pip install --upgrade pip *> $null
& $VPy -m pip install -q -r requirements.txt
if ($LASTEXITCODE -ne 0) { Die 'dependency installation failed (are you online?)' }
Ok 'dependencies installed'

Step 'Preparing configuration'
$EnvFile = Join-Path $ProjectRoot '.env'
if (Test-Path $EnvFile) {
    Ok '.env already exists - leaving it untouched'
} else {
    $key = & $VPy -c 'import secrets; print(secrets.token_urlsafe(36))'
    $dbPath = (Join-Path $ProjectRoot 'meduza-local.db') -replace '\\', '/'
    $lines = @(
        '# Meduza V - local (no-Docker) configuration, generated by install-local.ps1.'
        '# Demo mode: payments simulated, receipts printed to the log. Nothing is charged.'
        'ENVIRONMENT="development"'
        "DATABASE_URL=`"sqlite+aiosqlite:///$dbPath`""
        'PAYMENT_PROVIDER="fake"'
        'EMAIL_BACKEND="console"'
        'EMAIL_FROM_NAME="Meduza V"'
        'STRIPE_WEBHOOK_SECRET="whsec_local_demo_secret"'
        "ADMIN_API_KEY=`"$key`""
        "PUBLIC_BASE_URL=`"http://127.0.0.1:$Port`""
        'SHIPPING_FLAT_MINOR="500"'
        'RATE_LIMIT_ENABLED="true"'
        'REDIS_URL=""'
        'LOG_FORMAT="console"'
    )
    # UTF-8 without a BOM and with LF endings: pydantic and the shell scripts
    # both read this file, and a BOM turns the first key into "﻿ENVIRONMENT".
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($EnvFile, ($lines -join "`n") + "`n", $utf8NoBom)
    Ok 'generated .env (SQLite, demo payments)'
    Warn 'demo mode: no real money moves; receipts go to the log'
}

# Load .env into this process so alembic and the seeder see it.
foreach ($line in Get-Content $EnvFile) {
    if ($line -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$') {
        $name = $Matches[1]
        $value = $Matches[2].Trim().Trim('"')
        [Environment]::SetEnvironmentVariable($name, $value, 'Process')
    }
}

Step 'Creating the database'
& $VPy -m alembic upgrade head *> $null
if ($LASTEXITCODE -ne 0) { Die 'migrations failed' }
Ok 'schema applied to meduza-local.db'

if (-not $NoSeed) {
    & $VPy -m app.seed *> $null
    if ($LASTEXITCODE -eq 0) { Ok 'sample catalog loaded (re-running will not duplicate it)' }
    else { Warn 'catalog seed failed; the shop still runs' }
}

$startCmd = Join-Path $ProjectRoot 'start-local.ps1'
@"
# Start Meduza V locally (web + worker). Generated by install-local.ps1.
Set-Location `$PSScriptRoot
foreach (`$line in Get-Content .env) {
    if (`$line -match '^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)`$') {
        [Environment]::SetEnvironmentVariable(`$Matches[1], `$Matches[2].Trim().Trim('"'), 'Process')
    }
}
`$vpy = Join-Path `$PSScriptRoot '$VenvBin' '$PyExe'
Start-Process -NoNewWindow `$vpy '-m', 'app.worker'
& `$vpy -m uvicorn app.main:app --host 127.0.0.1 --port $Port
"@ | Set-Content -Path $startCmd -Encoding utf8
Ok 'wrote start-local.ps1'

if ($NoStart) {
    Write-Host "`nSet up. Start it with: .\start-local.ps1`n" -ForegroundColor Green
    exit 0
}

Step 'Starting the shop'
$Url = "http://127.0.0.1:$Port"
function Probe($path) {
    try { (Invoke-WebRequest -Uri "$Url$path" -TimeoutSec 3 -UseBasicParsing).StatusCode -eq 200 }
    catch { $false }
}

if (Probe '/healthz') {
    Warn "something is already serving on port $Port"
} else {
    # Two deliberate choices here.
    #
    # Redirection is done by the shell rather than by Start-Process's
    # -RedirectStandardOutput: that switch hands the child a pipe owned by
    # *this* process, so the moment the installer exits the pipe breaks and the
    # shop's log silently stops after its first line. Letting cmd.exe (or sh)
    # own a real file outlives us.
    #
    # And the process is launched through .NET rather than Start-Process,
    # because Start-Process flattens -ArgumentList back into one string and
    # re-parses it, which mangles the quoting around the interpreter path.
    $shell = if ($OnWindows) { 'cmd.exe' } else { '/bin/sh' }
    $flag = if ($OnWindows) { '/c' } else { '-c' }
    $serve = "`"$VPy`" -m uvicorn app.main:app --host 127.0.0.1 --port $Port --log-level warning > server.log 2>&1"
    $work = "`"$VPy`" -m app.worker > worker.log 2>&1"
    # Record what we started. The uninstaller cannot reliably find these by
    # process path: on Linux and macOS .venv/bin/python is a symlink, so the
    # reported path is the system interpreter, outside the project entirely.
    $pids = foreach ($command in @($serve, $work)) {
        $psi = New-Object System.Diagnostics.ProcessStartInfo
        $psi.FileName = $shell
        $psi.ArgumentList.Add($flag)
        $psi.ArgumentList.Add($command)
        $psi.WorkingDirectory = $ProjectRoot
        $psi.UseShellExecute = $false
        $psi.CreateNoWindow = $true
        ([System.Diagnostics.Process]::Start($psi)).Id
    }
    Set-Content -Path (Join-Path $ProjectRoot '.meduza-local.pid') -Value $pids
    foreach ($i in 1..60) { if (Probe '/healthz') { break }; Start-Sleep -Milliseconds 250 }
}
if (-not (Probe '/healthz')) { Die 'the shop did not start; see server.log' }
Ok 'health check passed'
if (Probe '/readyz') { Ok 'readiness passed (database reachable)' } else { Warn 'readiness failing - see server.log' }

$adminKey = (Select-String -Path $EnvFile -Pattern '^ADMIN_API_KEY=' | Select-Object -First 1).Line -replace '^ADMIN_API_KEY=', '' -replace '"', ''

Write-Host ""
Write-Host "Meduza V is running." -ForegroundColor Green
Write-Host ""
Write-Host "  Storefront   $Url"
Write-Host "  API docs     $Url/docs"
Write-Host "  Admin key    $adminKey"
Write-Host ""
Write-Host "  Restart later:  .\start-local.ps1"
Write-Host "  Logs:           Get-Content -Wait server.log"
Write-Host ""
Write-Host "Demo mode" -ForegroundColor Yellow -NoNewline
Write-Host " - payments are simulated and receipts are printed to worker.log."
Write-Host "For a real shop use installer\install.ps1 (Docker + PostgreSQL) and put your"
Write-Host "Stripe keys in .env: SQLite cannot hold the row locks that stop two customers"
Write-Host "buying the last item at once."
Write-Host ""

if ($OnWindows) { Start-Process $Url }
exit 0
