#!/usr/bin/env bash
# Meduza V — local install, no Docker required (Linux / macOS).
#
# Runs the whole shop from one Python virtualenv against a SQLite file:
# web + background worker + storefront. Intended for demos, evaluation and
# single-operator use on one machine.
#
#   ./installer/install-local.sh              install and start
#   ./installer/install-local.sh --port 8100  serve on another port
#   ./installer/install-local.sh --no-start   set up only
#
# NOT the production path. SQLite has no row locking, so the protection against
# two customers buying the last item at the same time is weaker than on
# PostgreSQL. For a real shop use installer/install.sh (Docker + PostgreSQL).

set -Eeuo pipefail
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PORT=8000; START=1; SEED=1
while [ $# -gt 0 ]; do
  case "$1" in
    --port) PORT="${2:?}"; shift ;;
    --no-start) START=0 ;;
    --no-seed) SEED=0 ;;
    -h|--help) sed -n '2,16p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac; shift
done

if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  BOLD=$'\033[1m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; DIM=$'\033[2m'; OFF=$'\033[0m'
else BOLD=""; GREEN=""; YELLOW=""; RED=""; DIM=""; OFF=""; fi
step(){ printf '%s==>%s %s\n' "$BOLD" "$OFF" "$1"; }
ok(){ printf '    %s+%s %s\n' "$GREEN" "$OFF" "$1"; }
warn(){ printf '    %s!%s %s\n' "$YELLOW" "$OFF" "$1"; }
die(){ printf '\n%serror:%s %s\n' "$RED" "$OFF" "$1" >&2; exit 1; }

cd "$PROJECT_ROOT"
printf '\n%sMeduza V — local install (no Docker)%s\n%s%s%s\n\n' "$BOLD" "$OFF" "$DIM" "$PROJECT_ROOT" "$OFF"

step "Checking Python"
PY=""
for c in python3 python; do
  command -v "$c" >/dev/null 2>&1 || continue
  "$c" -c 'import sys; sys.exit(0 if sys.version_info >= (3,11) else 1)' 2>/dev/null && { PY="$c"; break; }
done
[ -n "$PY" ] || die "Python 3.11 or newer is required.
    https://www.python.org/downloads/"
ok "$("$PY" --version 2>&1)"

step "Creating the virtual environment"
VENV="$PROJECT_ROOT/.venv"; VPY="$VENV/bin/python"
[ -x "$VPY" ] && ok "reusing existing .venv" || {
  "$PY" -m venv "$VENV" || die "could not create a virtualenv (Debian/Ubuntu: sudo apt install python3-venv)"
  ok "created .venv"; }

step "Installing dependencies"
"$VPY" -m pip install --upgrade pip >/dev/null 2>&1 || true
"$VPY" -m pip install -q -r requirements.txt || die "dependency installation failed (are you online?)"
ok "dependencies installed"

step "Preparing configuration"
if [ -f .env ]; then
  ok ".env already exists — leaving it untouched"
else
  umask 077
  KEY="$("$VPY" -c 'import secrets; print(secrets.token_urlsafe(36))')"
  cat > .env <<EOF
# Meduza V — local (no-Docker) configuration, generated by install-local.sh.
# Demo mode: payments simulated, receipts printed to the log. Nothing is charged.
ENVIRONMENT="development"
DATABASE_URL="sqlite+aiosqlite:///$PROJECT_ROOT/meduza-local.db"
PAYMENT_PROVIDER="fake"
EMAIL_BACKEND="console"
EMAIL_FROM_NAME="Meduza V"
STRIPE_WEBHOOK_SECRET="whsec_local_demo_secret"
ADMIN_API_KEY="$KEY"
PUBLIC_BASE_URL="http://127.0.0.1:$PORT"
SHIPPING_FLAT_MINOR="500"
RATE_LIMIT_ENABLED="true"
REDIS_URL=""
LOG_FORMAT="console"
EOF
  chmod 600 .env 2>/dev/null || true
  ok "generated .env (SQLite, demo payments)"
  warn "demo mode: no real money moves; receipts go to the log"
fi
set -a; . ./.env; set +a

step "Creating the database"
"$VPY" -m alembic upgrade head >/dev/null 2>&1 || die "migrations failed"
ok "schema applied to $(basename "${DATABASE_URL##*/}")"
if [ "$SEED" -eq 1 ]; then
  "$VPY" -m app.seed >/dev/null 2>&1 && ok "sample catalog loaded (re-running will not duplicate it)" \
    || warn "catalog seed failed; the shop still runs"
fi

cat > start-local.sh <<EOF
#!/usr/bin/env bash
# Start Meduza V locally (web + worker). Generated by install-local.sh.
cd "\$(dirname "\$0")"
set -a; . ./.env; set +a
.venv/bin/python -m app.worker &
WORKER=\$!
trap 'kill \$WORKER 2>/dev/null' EXIT
.venv/bin/uvicorn app.main:app --host 127.0.0.1 --port $PORT
EOF
chmod +x start-local.sh
ok "wrote start-local.sh"

[ "$START" -eq 1 ] || { printf '\n%sSet up. Start it with:%s ./start-local.sh\n\n' "$GREEN" "$OFF"; exit 0; }

step "Starting the shop"
if curl -fsS "http://127.0.0.1:$PORT/healthz" >/dev/null 2>&1; then
  warn "something is already serving on port $PORT"
else
  nohup "$VENV/bin/uvicorn" app.main:app --host 127.0.0.1 --port "$PORT" --log-level warning > server.log 2>&1 &
  echo $! > .meduza-local.pid
  nohup "$VPY" -m app.worker > worker.log 2>&1 &
  echo $! >> .meduza-local.pid
  for _ in $(seq 1 60); do curl -fsS "http://127.0.0.1:$PORT/healthz" >/dev/null 2>&1 && break; sleep 0.25; done
fi
curl -fsS "http://127.0.0.1:$PORT/healthz" >/dev/null 2>&1 || die "the shop did not start; see server.log"
ok "health check passed"
curl -fsS "http://127.0.0.1:$PORT/readyz" >/dev/null 2>&1 && ok "readiness passed (database reachable)" || warn "readiness failing — see server.log"

URL="http://127.0.0.1:$PORT"
cat <<EOF

${GREEN}${BOLD}Meduza V is running.${OFF}

  Storefront   ${URL}
  API docs     ${URL}/docs
  Admin key    $(grep '^ADMIN_API_KEY=' .env | cut -d= -f2- | tr -d '"')

  Restart later:  ./start-local.sh
  Logs:           tail -f server.log worker.log

${YELLOW}Demo mode${OFF} — payments are simulated and receipts are printed to worker.log.
For a real shop use ${BOLD}installer/install.sh${OFF} (Docker + PostgreSQL) and put your
Stripe keys in .env: SQLite cannot hold the row locks that stop two customers
buying the last item at once.

EOF
command -v xdg-open >/dev/null 2>&1 && xdg-open "$URL" >/dev/null 2>&1 &
exit 0
